### PR TITLE
More elegant method to prevent other files to be downloadable

### PR DESCRIPTION
**Pull request by npes87184**
Instead of creating a temp dir and chdir into it. We can simply return
403 if the request path is not recognized.

Signed-off-by: yuchenlin <npes87184@gmail.com>

### CODE REVIEW

**Comment by sdushantha** [comment]
Thank you for your PR! Yes, sending a 403 is very good idea.

Unfortunately there is one problem. Transferring folder/directories wont work. When you open the link from the QR code on your phone, it opens the directory where you ran  ```qr-filetransfer```. Also, when try to access any of the files or folders in that directory, you get 403. 

I am not sure how to fix that because am really new to Python `class`, so I dont really know whats really happening in the class you made. :/

**Comment by npes87184** [comment]
Hi,

Oops, thank you for your testing.
However, there are no computer in my hand.
I will try to fix it Monday. 

Yu-Chen Lin

**Comment by npes87184** [comment]
Hi, @sdushantha 

Can you please provide more detail about the problem?

In my environment, I can transfer the folder.

```
./qr-filetransfer/qr-filetransfer ../TheCruelWorld
```

And the link will like `http://192.168.43.172:18527/TheCruelWorld.zip`
After scaning the QRCode, my phone downloaded TheCruelWorld.zip correctly.

Thanks,
Yu-Chen Lin

**Comment by sdushantha** [comment]
@npes87184 
Thats strange. I will test it again and will also provide some more details when I get some time this week

**Comment by sdushantha** [comment]
Hi @npes87184,

I made small video showing what is happening. 
https://photos.app.goo.gl/WMzGnQiyHMPAWUuV8

**Comment by npes87184** [comment]
Hi, @sdushantha 

Thank you for your video.
The problem is in the trailing slash, which leads to wrong behavior of `os.path.basename`.
I have fixed it by using `os.path.normpath` first.

You can try it again.

Thanks,
Yu-Chen Lin

**Comment by sdushantha** [comment]
Hey @npes87184,

I can confirm that it is fixed now.
There is another small issue. It will run even though you give an invalid filename and create a QR code. 
Could you fix that?

**Comment by npes87184** [comment]
Hi, @sdushantha 

I have fixed this problem.

Thanks,
Yu-Chen Lin

**Comment by sdushantha** [comment]
Hi, @npes87184 

Thank you for fixing that. It looks like that everything is working perfectly now :)

**Pull request merged**
