### PR TITLE
Added Windows support (issue #13)

### PR DESCRIPTION
**Pull request by gomercin**
Retrieves SSID from netsh output
Does not check if valid result had been found (similar with other OSs)

Put SIGSTP line under "if" as it does not work on Windows

### CODE REVIEW

**Comment by sdushantha** [comment]
Thank you!

It looks like there are some conflicts. I am sure that is because I moved the ```qr-filetransfer.py``` to ```qr-filetransfer/qr-filetransfer```. Do you know how to fix these conflicts?

**Comment by gomercin** [comment]
Hi there, sure I will have a look.

My mistake actually, I should have rebased again before pushing the changes
:)

**Comment by sdushantha** [comment]
No worries :)

**Comment by sdushantha** [comment]
Great! Thank you for your help.

**Comment by gomercin** [comment]
Should work now. 

As a side note: for windows print_tty prints glibberish while print_ascii works, if it works on linux and mac as well, it might be worth changing

**Comment by sdushantha** [comment]
```print_ascii``` works on Linux and MacOS but ```print_tty``` looks much nicer. I think we use ```print_ascii``` for Windows users and  ```print_tty``` for MacOS and Linux.

**Pull request merged**
