### PR TITLE
Clean up temporary zip file

### PR DESCRIPTION
**Pull request by CedArctic**
If the user decides to use a directory (folder) as an argument, a zip file will be created and then copied to the temporary folder. While the temporary folder gets removed, the first created zip file remains, this takes care of it by creating a variable (delete_zip) initialized to 0 and then changed to a the zip path if a zip gets created. Upon exiting a check is made whether the variable is anything other than 0, if that's the case the zip file gets deleted.

### CODE REVIEW

**Comment by sdushantha** [comment]
There is one problem with your code, there is a ```inconsistent use of tabs and spaces in indentation``` in some of the lines. If you can fix that, I will merge this PR

**Comment by CedArctic** [comment]
@sdushantha done. 😃

**Comment by sdushantha** [comment]
thank you :grinning:

**Comment by CedArctic** [comment]
You're welcome 😁

**Pull request merged**
